/* Base layout that simply loads the global CSS */
import './globals.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: {
  children: ReactNode,
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
